#!/usr/bin/env bash
#
# render-formula.sh — print the Homebrew formula for a released version.
#
# Lives here rather than inside release.yml so the formula can be rendered and
# read WITHOUT cutting a release: `brew` will not tell you a formula is wrong
# until someone installs it, and by then the tag is public and immutable.
#
# Usage:
#   scripts/render-formula.sh <version> <sha256sums-file>
#   scripts/render-formula.sh 0.2.0 SHA256SUMS > Formula/mailbox.rb
#
# The sums file is the one the release build publishes: one `<sha256>  <file>`
# line per platform tarball, i.e. the output of `shasum -a 256 *.tar.gz`.
set -euo pipefail

# Whose releases the formula's URLs point at. Defaults to this project so the
# script runs standalone; release.yml passes GITHUB_REPOSITORY, so a rename or a
# fork does not need a second edit here to publish working URLs.
SOURCE_REPO="${MAILBOX_RELEASE_REPO:-mikey-relevanceai/agent-mailbox}"
OWNER="${SOURCE_REPO%%/*}"
REPO="${SOURCE_REPO#*/}"

die() { echo "error: $*" >&2; exit 1; }

[[ $# -eq 2 ]] || die "usage: render-formula.sh <version> <sha256sums-file>"
VERSION="$1"
SUMS="$2"

[[ "${VERSION}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || die "not an X.Y.Z version: ${VERSION}"
[[ -r "${SUMS}" ]] || die "cannot read sums file: ${SUMS}"
# Check the shape before trusting the split above: with no `/`, both `%%/*` and
# `#*/` leave the string untouched, so OWNER and REPO silently become the SAME
# value and the formula renders plausible-looking URLs that 404.
[[ "${SOURCE_REPO}" =~ ^[^/]+/[^/]+$ ]] || die "not an OWNER/REPO: ${SOURCE_REPO}"

# Look a checksum up by tarball name. A missing entry is fatal: a formula that
# ships a blank or stale sha256 fails at `brew install` time on a user's machine,
# which is far too late to find out a build job silently produced nothing.
sha_for() {
  local target="$1"
  local file="mailbox-${VERSION}-${target}.tar.gz"
  local sha
  sha="$(awk -v f="${file}" '$2 == f || $2 == "*" f { print $1; exit }' "${SUMS}")"
  [[ -n "${sha}" ]] || die "no checksum for ${file} in ${SUMS}"
  [[ "${sha}" =~ ^[0-9a-f]{64}$ ]] || die "not a sha256 for ${file}: ${sha}"
  printf '%s' "${sha}"
}

url_for() {
  printf 'https://github.com/%s/%s/releases/download/v%s/mailbox-%s-%s.tar.gz' \
    "${OWNER}" "${REPO}" "${VERSION}" "${VERSION}" "$1"
}

ARM_DARWIN="aarch64-apple-darwin"
INTEL_DARWIN="x86_64-apple-darwin"
INTEL_LINUX="x86_64-unknown-linux-gnu"

# Drift guard. release.yml's build matrix and this script each enumerate the
# shipped targets, and nothing makes them move together. Adding a platform to the
# matrix without adding it here would publish a tarball the formula has no `url`
# block for, so `brew install` on that platform would keep failing with no sign
# that a build for it exists. Refuse to render rather than silently drop it.
KNOWN=" ${ARM_DARWIN} ${INTEL_DARWIN} ${INTEL_LINUX} "
while read -r _ file; do
  [[ -n "${file}" ]] || continue
  file="${file#\*}"
  target="${file#"mailbox-${VERSION}-"}"
  target="${target%.tar.gz}"
  case "${KNOWN}" in
    *" ${target} "*) ;;
    *) die "${SUMS} ships ${target}, which this formula has no url block for — add it to render-formula.sh" ;;
  esac
done <"${SUMS}"

# Resolve every checksum BEFORE the heredoc. Inside `$(...)` a `die` would exit
# only the subshell, so the template would still render — with `sha256 ""` where
# the missing sum should have been. Assignments abort the script under `set -e`,
# which is the only place these lookups can fail loudly.
SHA_ARM_DARWIN="$(sha_for "${ARM_DARWIN}")"
SHA_INTEL_DARWIN="$(sha_for "${INTEL_DARWIN}")"
SHA_INTEL_LINUX="$(sha_for "${INTEL_LINUX}")"

URL_ARM_DARWIN="$(url_for "${ARM_DARWIN}")"
URL_INTEL_DARWIN="$(url_for "${INTEL_DARWIN}")"
URL_INTEL_LINUX="$(url_for "${INTEL_LINUX}")"

cat <<FORMULA
# GENERATED by scripts/render-formula.sh in ${OWNER}/${REPO} — do not edit here.
# Every release overwrites this file; fix the generator, not the output.
class Mailbox < Formula
  desc "Wake idle coding agents on real-world events instead of polling"
  homepage "https://github.com/${OWNER}/${REPO}"
  version "${VERSION}"
  license "MIT"

  # The github-pr adapter reaches GitHub by shelling out to \`gh\`, and a missing
  # \`gh\` is FATAL rather than degraded: the adapter exits non-zero and the
  # supervisor gives up on that watch. Declaring it keeps the flagship use case
  # from failing after install rather than during it.
  # (Declared here, above the platform blocks, because \`brew style\` requires it.)
  depends_on "gh"

  on_macos do
    on_arm do
      url "${URL_ARM_DARWIN}"
      sha256 "${SHA_ARM_DARWIN}"
    end
    on_intel do
      url "${URL_INTEL_DARWIN}"
      sha256 "${SHA_INTEL_DARWIN}"
    end
  end

  on_linux do
    on_intel do
      url "${URL_INTEL_LINUX}"
      sha256 "${SHA_INTEL_LINUX}"
    end
  end

  def install
    # All three side by side. The bridge finds an adapter by looking next to its
    # own executable first, so co-location is the contract, not a convenience.
    bin.install "mailbox", "mailbox-stub-adapter", "mailbox-github-pr-adapter"
    doc.install "README.md"
  end

  def caveats
    <<~EOS
      Two setup commands remain, and this formula deliberately does not run them:
      both write to ~/.claude, outside Homebrew's prefix.

          mailbox harness install-skills
          mailbox harness install-hooks --mailbox-bin #{opt_bin}/mailbox

      Pass --mailbox-bin exactly as shown. #{opt_bin} is the path Homebrew
      re-points on every upgrade; the versioned path behind it is deleted by
      \`brew upgrade\`, which would leave the hook pointing at a binary that is
      gone — silently, and only for peer messages.

      The wake also needs CLAUDE_CODE_HARBOR_KITE=1 in ~/.claude/settings.json
      and a session restart. Neither this formula nor install-hooks sets it.
      Check what is missing with:

          mailbox doctor
    EOS
  end

  test do
    # The version contract: a bare semver as an unadorned leading token. The
    # git-hash suffix \`mailbox --version\` also prints is fine — this is a
    # substring match — but reformatting the semver itself breaks this test.
    assert_match version.to_s, shell_output("#{bin}/mailbox --version")

    # Co-location again: adapter discovery resolves siblings of the running
    # binary, so an install that scattered these would pass the version check
    # above and still fail the first time anyone ran \`mailbox watch\`.
    assert_path_exists bin/"mailbox-stub-adapter"
    assert_path_exists bin/"mailbox-github-pr-adapter"
  end
end
FORMULA
